# Generated by Django 3.1.1 on 2020-09-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Paciente')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
