# Generated by Django 3.1.1 on 2020-11-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201024_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='considerations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='max_threshold',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='min_threshold',
            field=models.FloatField(null=True),
        ),
    ]
