# Generated by Django 3.1.1 on 2020-10-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
